---
apiVersion: v1
kind: Pod
metadata:
  name: etcd-server
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
  - name: etcd-container
    image: dumplingtech/etcd:latest
    env:
    - {"name": "ETCD_CLIENT_PORT", "value": "4001"}
    - {"name": "ETCD_SERVER_PORT", "value": "7001"}
    - {"name": "ETCD_LISTEN_PEER_URLS", "value": "http://0.0.0.0:7001"}
    - {"name": "ETCD_INITIAL_ADVERTISE_PEER_URLS", "value": "http://{{ ansible_default_ipv4.address }}:7001"}
    - {"name": "ETCD_LISTEN_CLIENT_URLS", "value": "http://0.0.0.0:4001"}
    - {"name": "ETCD_ADVERTISE_CLIENT_URLS", "value": "http://{{ ansible_default_ipv4.address }}:4001"}
    - {"name": "ETCD_DATA_DIR", "value": "/var/etcd/data"}
    - {"name": "ETCD_SNAPSHOT_COUNT", "value": "1000"}
    - {"name": "ETCD_ELECTION_TIMEOUT", "value": "2000"}
    - {"name": "ETCD_HEARTBEAT_INTERVAL", "value": "400"}
    - {"name": "ETCD_NAME", "value": "{{ ansible_default_ipv4.address }}"}
    - {"name": "ALERT_URL", "value": "{{ alert_url }}"}
    - {"name": "EC2_REGION", "value": "{{ ec2_region }}"}
    - {"name": "DOMAIN", "value": "{{ internal_domain }}"}

    resources:
      requests:
        cpu: 200m
    livenessProbe:
      httpGet:
        host: 127.0.0.1
        port: 4001
        path: "/health"
      initialDelaySeconds: 15
      timeoutSeconds: 15
    ports:
    - name: serverport
      containerPort: 7001
      hostPort: 7001
    - name: clientport
      containerPort: 4001
      hostPort: 4001
    volumeMounts:
    - name: varetcd
      mountPath: "/var/etcd"
      readOnly: false
    - name: varlogetcd
      mountPath: "/var/log/etcd.log"
      readOnly: false
  volumes:
  - name: varetcd
    hostPath:
      path: "/var/etcd"
  - name: varlogetcd
    hostPath:
      path: "/var/log/etcd.log"
