- name: create tmp directory
  become: true
  file: path=/tmp/flannel state=directory mode=0755

- name: download flannel install scripts
  become: true
  template: src={{item}} dest=/tmp/flannel/ mode=0755
  with_fileglob:
    - ../templates/*

- name: run flannel install script
  become: true
  command: /tmp/flannel/download-flannel.sh
