k8s_version: 1.3.4
etcd_version: 2.3.7
flannel_version: 0.5.5

# will be used as the Internal dns domain name if DNS is enabled. Services
# will be discoverable under <service-name>.<namespace>.svc.<domainname>, e.g.
# myservice.default.svc.cluster.local
cluster_domain: cluster.local

# cluster name used in kubeconfig
cluster_name: dumpling

# must change this to point to the kube master
api_server_address: 172.20.0.221

# Account name of remote user. Ansible will use this user account to ssh into
# the managed machines. The user must be able to use sudo without asking
# for password unless ansible_sudo_pass is set
ansible_ssh_user: admin

# password for the ansible_ssh_user. If this is unset you will need to set up
# ssh keys so a password is not needed.
#ansible_ssh_pass: password

# If a password is needed to sudo to root that password must be set here
#ansible_sudo_pass: password

# A list of insecure registrys you might need to define
insecure_registrys:
#  - "gcr.io"

# Required for CoreOS. CoreOS does not include a Python interpreter. The
# pre-ansible role installs a python interpreter to /opt/bin/. For more
# information see https://coreos.com/blog/managing-coreos-with-ansible.html
#ansible_python_interpreter: "PATH=/opt/bin:$PATH python"

# If you need a proxy for the docker daemon define these here
#http_proxy: "http://proxy.example.com:3128"
#https_proxy: "http://proxy.example.com:3128"
#no_proxy: "127.0.0.1,localhost,docker-registry.somecorporation.com"

# The port that the Kubernetes apiserver component listens on.
kube_master_api_port: 443

# Kubernetes internal network for services.
# Kubernetes services will get fake IP addresses from this range.
# This range must not conflict with anything in your infrastructure. These
# addresses do not need to be routable and must just be an unused block of space.
kube_service_addresses: 10.0.0.0/24

kube_dns_address: 10.0.0.10

# can only be master/minion
kube_role: minion

# Network implementation (flannel|opencontrail|contiv)
networking: flannel

# External network
# opencontrail_public_subnet: 10.1.4.0/24

# Underlay network
# opencontrail_private_subnet: 192.168.1.0/24

# Data interface
# opencontrail_interface: eth1

# Flannel internal network (optional). When flannel is used, it will assign IP
# addresses from this range to individual pods.
# This network must be unused in your network infrastructure!
flannel_subnet: 10.2.0.0

# Flannel internal network total size (optional). This is the prefix of the
# entire flannel overlay network.  So the entirety of 172.16.0.0/12 must be
# unused in your environment.
flannel_prefix: 16

# Flannel internal network (optional). This is the size allocation that flannel
# will give to each node on your network.  With these defaults you should have
# room for 4096 nodes with 254 pods per node.
flannel_host_prefix: 24

# common kubelet daemon argument
kube_common_args: --cloud-provider=aws --config=/etc/kubernetes/manifests --allow-privileged=True --v=2 --cluster-dns={{ kube_dns_address }} --cluster-domain={{ cluster_domain }} --configure-cbr0=false --non-masquerade-cidr=10.0.0.0/8 --cgroup-root=docker --babysit-daemons=true

# master kubelet argument
kube_master_args: --pod-cidr={{ flannel_subnet }}/24 --enable-debugging-handlers=false --hairpin-mode=none

# minion kubelet argument
kube_minion_args: --api-servers=https://{{ api_server_address }} --enable-debugging-handlers=true

# Create a default Contiv network for providing connectivity among pods
# networking: contiv must be set to use Contiv networking
#contiv_default_network: true
#contiv_default_subnet: 172.16.0.0/16
#contiv_default_gw: 172.16.0.1

# Set to false to disable logging with elasticsearch
cluster_logging: true

# Turn to false to disable cluster monitoring with heapster and influxdb
cluster_monitoring: true

# Turn to false to disable the kube-ui addon for this cluster
kube-ui: true

# Turn to false to disable the kube-dash addon for this cluster
kube-dash: true

# Turn this varable to 'false' to disable whole DNS configuration.
dns_setup: true
# How many replicas in the Replication Controller
dns_replicas: 1

# There are other variable in roles/kubernetes/defaults/main.yml but changing
# them comes with a much higher risk to your cluster. So proceed over there
# with caution.

# See kube documentation for apiserver runtime config options.  Example below enables HPA, deployments features.
# apiserver_extra_args: "--runtime-config=extensions/v1beta1/deployments=true"

ec2_region: us-west-2
internal_domain: dumplingtech.io

# replace this with slack hook later
alert_url: http://localhost
