- name: create tmp directory
  become: true
  file: path=/tmp/etcd state=directory mode=0755

- name: download etcd install scripts
  become: true
  template: src={{item}} dest=/tmp/etcd/ mode=0755
  with_fileglob:
    - ../templates/*

- name: run etcd install script
  become: true
  command: /tmp/etcd/download.sh
