---
# This playbook deploys a kubernetes cluster
# with the default addons.

- hosts: all_hosts
  roles:
    - etcd
  tags:
    - etcd

- hosts: all_hosts
  roles:
    - flannel
  tags:
    - flannel


- hosts: all_hosts
  become: true
  roles:
    - docker
  tags:
    - docker

- hosts: all_hosts
  become: true
  roles:
    - kubelet
  tags:
    - kubelet

